#! /bin/bash

# Build the plugin CSS
npm install --frozen-lockfile
npm run css

# Create zip from the custom_components/auth_oidc directory
# HACS wants only the contents of this dir in a zip
cd custom_components/auth_oidc/
zip -r ../../hass-oidc-auth.zip ./*